-- 1. Tabla: Bloc
CREATE TABLE bloc (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- 2. Tabla: Tag
CREATE TABLE tag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    importance_level INTEGER NOT NULL CHECK (importance_level BETWEEN 1 AND 10)
);

-- 3. Tabla: Task
CREATE TABLE task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (char_length(title) > 0),
    due_date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    estimated_hours NUMERIC NOT NULL CHECK (estimated_hours > 0),
    bloc_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    
    CONSTRAINT fk_bloc FOREIGN KEY (bloc_id) REFERENCES bloc(id) ON DELETE CASCADE,
    CONSTRAINT fk_tag FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE RESTRICT
);

-- 4. Tabla: WorkDay (Sin la columna date)
CREATE TABLE work_day (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available_hours NUMERIC NOT NULL CHECK (available_hours >= 0)
);

-- Índices para optimizar velocidad en Supabase
CREATE INDEX idx_task_due_date ON task(due_date);
CREATE INDEX idx_task_completed ON task(completed);
CREATE INDEX idx_task_bloc_id ON task(bloc_id);
CREATE INDEX idx_task_tag_id ON task(tag_id);